### ISSUE TITLE
Images for website

### ISSUE THREAD

**Issue by kumanan12** [kumanan12/faruk-biriyani#2]
Look in this web site.
https://unsplash.com/s/photos/biryani

**Comment by emmacyrus** [comment]
Some Picture Options:

- https://media.istockphoto.com/id/1442917936/photo/extremely-delicious-and-spicy-chicken-biryani.jpg?s=612x612&w=0&k=20&c=tCh42uU01-4_ZEfboMnDGwxhVTBnbXV1iM1fNyUXCg8= 

- https://media.istockphoto.com/id/1305452646/photo/biryani.jpg?s=612x612&w=0&k=20&c=qndxBx3hBmx6tCkKPUVd8-V4P3QhH4xAkzjU84KqAx4=

- https://media.istockphoto.com/id/501137061/photo/chicken-biryani-1-4.jpg?s=612x612&w=0&k=20&c=4YH3uPuv2iNyNTemn5bTxCyst608o3WDZNyATnibDsg=

- https://media.istockphoto.com/id/519492397/photo/delhi-biryani.jpg?s=612x612&w=0&k=20&c=tJJgEYOkrhlsIhkjjT4qqJY0t79PJncEVqUvR_l3fxU=

- https://media.istockphoto.com/id/467633639/photo/hyderabadi-biryani-a-popular-chicken-or-mutton-dish.jpg?s=612x612&w=0&k=20&c=Ct0hrSefZCx6Z8EYwwdeO1URC88wfol9ffHL7rycx-0=

- https://media.istockphoto.com/id/1282783734/photo/indian-traditional-bombay-biryani-chicken-biryani-is-a-special-pakistani-food.jpg?s=612x612&w=0&k=20&c=Oh3Eq__uaVutYQ2eU6PAY2Ur4vMg2cs9QCWmpeIF9Vw=

- https://media.istockphoto.com/id/466843497/photo/hyderabadi-biryani-is-a-popular-chicken-or-mutton-based-dish.jpg?s=612x612&w=0&k=20&c=XfqRljV8IrORtNoPYACFHF7oW_gALBaXGKboD128vkE=

- https://media.istockphoto.com/id/980036840/photo/gosht-or-lamb-biryani-prepared-in-basmati-rice-served-with-yogurt-dip-in-terracotta-bowl.jpg?s=612x612&w=0&k=20&c=jFTBXVyQkPmt_3GE1hOSlraqBe_qIIDN7zckiHUqAWc=
